### ISSUE TITLE
wow!

### ISSUE THREAD

**Issue by entomb** [JosePedroDias/tenbyten#1]
This is beautifull, I'm code gay for your JS. love the way you are solving those matrixs,

Please, I know this is only for fun, but be more verbose on your vars/ids so I can read this in all its glory!

**Comment by JosePedroDias** [comment]
Thx man. My motto developing this was KISS and it is paying off. Don't know how deliberate was it, maybe due to coding the first version on jsbin - http://jsbin.com/cijaba/latest/ but it went a bit like code golf. 
I took a break this weekend in the countryside without laptop but I plan on finishing the server-checked version during the week and I'll try to keep it readable O:)  (BTW this is because several players requested a high score table) 
Cheers
